import { formatComment, buildInlineComments } from '../core/engine.js';
import type { PrMetadata, Review, PostReviewOptions } from '../types.js';

type LogFn = (...args: unknown[]) => void;

const BB_API = 'https://api.bitbucket.org/2.0';

export function detect(): boolean {
  return !!process.env.BITBUCKET_BUILD_NUMBER;
}

export async function getPrMetadata(token?: string): Promise<PrMetadata> {
  const prId = process.env.BITBUCKET_PR_ID;
  if (!prId) throw new Error('BITBUCKET_PR_ID not set. Is this running on a PR pipeline?');

  const workspace = process.env.BITBUCKET_WORKSPACE;
  const repoSlug = process.env.BITBUCKET_REPO_SLUG;

  if (!workspace || !repoSlug) {
    throw new Error('BITBUCKET_WORKSPACE and BITBUCKET_REPO_SLUG must be set.');
  }

  const prData = await bbFetch(
    `${BB_API}/repositories/${workspace}/${repoSlug}/pullrequests/${prId}`,
    { headers: authHeaders(token) },
  );
  const pr = JSON.parse(prData);

  return {
    prNumber: parseInt(prId, 10),
    prTitle: pr.title || '',
    prAuthor: pr.author?.display_name || pr.author?.nickname || '',
    prBody: pr.description || '',
    baseBranch: pr.destination?.branch?.name || 'main',
  };
}

export async function postReview(
  review: Review,
  { prNumber, token, postReview: shouldPost = true, log = console.log }: PostReviewOptions,
): Promise<void> {
  const workspace = process.env.BITBUCKET_WORKSPACE;
  const repoSlug = process.env.BITBUCKET_REPO_SLUG;
  const commitHash = process.env.BITBUCKET_COMMIT;

  if (!workspace || !repoSlug) {
    throw new Error('BITBUCKET_WORKSPACE and BITBUCKET_REPO_SLUG must be set.');
  }

  const baseUrl = `${BB_API}/repositories/${workspace}/${repoSlug}/pullrequests/${prNumber}`;
  const headers = authHeaders(token);

  // Clean up previous AI review comments
  log('Cleaning up previous AI review comments...');
  await deleteStaleComments(baseUrl, headers, log);

  // Post inline comments
  const inlineComments = buildInlineComments(review.issues);
  let inlinePosted = 0;

  for (const comment of inlineComments) {
    try {
      await bbFetch(`${baseUrl}/comments`, {
        method: 'POST',
        headers: { ...headers, 'Content-Type': 'application/json' },
        body: JSON.stringify({
          content: { raw: comment.body, markup: 'markdown' },
          inline: {
            path: comment.path,
            to: comment.line,
            ...(comment.start_line ? { from: comment.start_line } : {}),
          },
        }),
      });
      inlinePosted++;
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      log(`Warning: Failed to post inline comment on ${comment.path}:${comment.line}: ${message}`);
    }
  }

  log(`Posted ${inlinePosted} inline comment(s).`);

  // Post summary comment
  const summaryBody = formatComment(review);
  await bbFetch(`${baseUrl}/comments`, {
    method: 'POST',
    headers: { ...headers, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      content: { raw: summaryBody, markup: 'markdown' },
    }),
  });

  if (!shouldPost) return;

  // Set build status
  if (commitHash) {
    const statusUrl = `${BB_API}/repositories/${workspace}/${repoSlug}/commit/${commitHash}/statuses/build`;
    try {
      await bbFetch(statusUrl, {
        method: 'POST',
        headers: { ...headers, 'Content-Type': 'application/json' },
        body: JSON.stringify({
          state: review.approve ? 'SUCCESSFUL' : 'FAILED',
          key: 'ai-code-review',
          name: 'AI Code Review',
          description: review.approve
            ? 'AI review passed — no blocking issues found.'
            : `AI review found issues: ${review.summary}`.slice(0, 255),
          url: `https://bitbucket.org/${workspace}/${repoSlug}/pull-requests/${prNumber}`,
        }),
      });
      log(`Set build status: ${review.approve ? 'SUCCESSFUL' : 'FAILED'}`);
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      log(`Warning: Could not set build status: ${message}`);
    }
  }

  // Approve/unapprove as secondary signal
  if (review.approve) {
    try {
      await bbFetch(`${baseUrl}/approve`, { method: 'POST', headers });
      log('Approved PR.');
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      log(`Warning: Could not approve PR: ${message}`);
    }
  } else {
    try {
      await bbFetch(`${baseUrl}/approve`, { method: 'DELETE', headers });
    } catch {
      // May not have been approved previously — that's fine
    }
    log('PR not approved — issues found.');
  }
}

async function deleteStaleComments(baseUrl: string, headers: Record<string, string>, log: LogFn): Promise<void> {
  try {
    const response = await bbFetch(`${baseUrl}/comments?pagelen=100`, { headers });
    const data = JSON.parse(response);

    for (const comment of (data.values || [])) {
      if (comment.content?.raw?.includes('Generated by AI Code Review')) {
        try {
          await bbFetch(`${baseUrl}/comments/${comment.id}`, { method: 'DELETE', headers });
          log(`Deleted stale comment #${comment.id}.`);
        } catch (err: unknown) {
          const message = err instanceof Error ? err.message : String(err);
          log(`Warning: Could not delete comment #${comment.id}: ${message}`);
        }
      }
    }
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    log(`Warning: Could not list comments for cleanup: ${message}`);
  }
}

function authHeaders(token?: string): Record<string, string> {
  return token ? { Authorization: `Bearer ${token}` } : {};
}

async function bbFetch(url: string, opts: RequestInit = {}): Promise<string> {
  const response = await fetch(url, opts);
  if (!response.ok) {
    const body = await response.text();
    throw new Error(`Bitbucket API ${response.status}: ${body}`);
  }
  return response.text();
}
